version: '3.9'

services:
  ghidra:
    image: almohress/ghidra-server:10.0.4
    ports:
      - 13100:13100
      - 13101:13101 
      - 13102:13102 
    environment:
      - GHIDRA_USERS=admin testuser
      - GHIDRA_PUBLIC_HOSTNAME=0.0.0.0
    volumes:
      - ghidra_volume:/repos
volumes:
  ghidra_volume:
